In [4]:
import numpy as np

a1 = np.array([[1,2,3,],[10,20,30]])
print(a1)
print(a1.ndim)
print(a1.shape)
print(a1.size)

[[ 1  2  3]
 [10 20 30]]
2
(2, 3)
6


In [22]:
a2 = np.arange(20).reshape(4,5)
print(a2)
print(a2.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


In [20]:
a3 = a2.flatten() # 무조건 하나로 합치기
a3[4] = 200
print(a3)
a4 = a2.ravel()
a3[3] = 200
print(a4)

[  0   1   2 200 200   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[  0   1   2 200   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


In [27]:
print(a2)
print(a2.sum(axis=0))
print(a2.sum(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[30 34 38 42 46]
[10 35 60 85]


In [32]:
print(a2,a2.shape)
a3 =a2.T
print(a3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [54]:
a10 = np.arange(5,20).reshape(3,5)
print(len(a10))
a11=a10[:,2:4]
print(a11.sum(axis=0))

3
[36 39]
