In [4]:
import numpy as np

In [10]:
a1 = np.array([1,2,3,4,5])
list1 = [1,2,3,4,5]
print(list1)
print(a1)
print(type(a1))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [22]:
a2 = np.arange(10)
print(a2)
# 100이하 3의 배수
a3 = np.arange(3,100,3)
print('100이하 3의 배수 : ',a3)

# 1에서부터 10아래 0.5씩 증가는 숫자 
a4 = np.arange(0,10,0.3)
print(a4)

# lista= [1 for i in range(1.3,10,0.5)] 실수는 안됨

[0 1 2 3 4 5 6 7 8 9]
100이하 3의 배수 :  [ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7 3.  3.3 3.6 3.9 4.2 4.5 4.8 5.1
 5.4 5.7 6.  6.3 6.6 6.9 7.2 7.5 7.8 8.1 8.4 8.7 9.  9.3 9.6 9.9]


In [26]:
a4 = np.linspace(0,10,15) #0에서 10까지 15개로 나누기
print(a4)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [30]:
a5 = np.zeros(5)
print(a5)

a6 = np.ones(5)
print(a6)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [35]:
lista= [1,2,3.4,4.2]
a7 = np.array(lista)
print(a7)

listb = [1,2,'abc','def']
a8 = np.array(listb)
print(a8)

[1.  2.  3.4 4.2]
['1' '2' 'abc' 'def']


In [41]:
print(a7.dtype)
print(a7.ndim)
print(a7.shape)
print(a7.size)

print(a7.itemsize)
print(a7.data)

float64
1
(4,)
4
8


In [53]:
a10 = np.arange(10,100,5)
print(a10)
print(a10[a10%10==5])
#특정 인덱스
print(a10[5])
#스타트, 스탑
print(a10[:4])
x = (a10%10 ==5)
print(x)



[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[15 25 35 45 55 65 75 85 95]
35
[10 15 20 25]
[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True]


In [ ]:
a