In [5]:
import numpy as np

a1 = np.arange(30).reshape(5,6)
print(a1)
print('np.sum',np.sum(a1,axis=0))
print(np.add.reduce(a1,axis=0))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
np.sum [60 65 70 75 80 85]
[60 65 70 75 80 85]
