In [8]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(100,110)
print(a1,a2)
a3 = np.array([5]*10)
print(a3+5)

[0 1 2 3 4 5 6 7 8 9] [100 101 102 103 104 105 106 107 108 109]
[10 10 10 10 10 10 10 10 10 10]


In [11]:
# f(x) = 3x +5
# x = 0에서 100사이 작수일때 f(x)의 값
x = np.arange(0,101,2)
print(3*x+5)

[  5  11  17  23  29  35  41  47  53  59  65  71  77  83  89  95 101 107
 113 119 125 131 137 143 149 155 161 167 173 179 185 191 197 203 209 215
 221 227 233 239 245 251 257 263 269 275 281 287 293 299 305]


In [22]:
a2 = np.arange(30).reshape(5,6)
print(a2)
a3 = np.arange(6)
print(a3)
a4 = np.arange(100,130).reshape(5,6)
print(a4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[0 1 2 3 4 5]
[[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]
 [124 125 126 127 128 129]]


In [26]:
print(a2+a4)

# a2  : (5,6)
# a3  : (6,)
# a4  : (5,6)


[[100 102 104 106 108 110]
 [112 114 116 118 120 122]
 [124 126 128 130 132 134]
 [136 138 140 142 144 146]
 [148 150 152 154 156 158]]


In [30]:
a10 = np.arange(5*6*7*8)
print(a10)

[   0    1    2 ... 1677 1678 1679]


In [45]:
a15 = np.arange(15).reshape(5,3)
print(a15)
# axis 3개의 값 중
# 첫번째는 곱하기 2
# 두번째는 곱하기 10
# 세번짼느 곱하기 12
# axis1을 따라 합계 구하기
a15[:,0]=a15[:,0]*2
a15[:,1]=a15[:,1]*10
a15[:,2]=a15[:,2]*12
a16=np.sum(a15,axis=1)
print(a16)
      

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[ 34 106 178 250 322]


In [47]:
a15 = np.arange(15).reshape(5,3)
print(a15)
# axis 3개의 값 중
# 첫번째는 곱하기 2
# 두번째는 곱하기 10
# 세번짼느 곱하기 12
# axis1을 따라 합계 구하기
# 강사님이 한거
x = np.array([2,10,12])
print(np.sum(a15*x,axis=1))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[ 34 106 178 250 322]
